# Generated by Django 5.0.6 on 2025-05-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/', verbose_name='Аудиофайл'),
        ),
    ]
