# Generated by Django 5.0.6 on 2025-05-12 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaudio', '0003_album_likes_count_useractivity_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='kaudio.album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер трека'),
        ),
    ]
