# Generated by Django 5.0.6 on 2025-05-22 22:52

import kaudio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaudio', '0004_alter_track_album_alter_track_release_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=kaudio.models.get_album_image_path, verbose_name='Изображение обложки'),
        ),
        migrations.AddField(
            model_name='artist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=kaudio.models.get_artist_image_path, verbose_name='Изображение обложки'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=kaudio.models.get_playlist_image_path, verbose_name='Изображение обложки'),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=kaudio.models.get_track_image_path, verbose_name='Изображение обложки'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=kaudio.models.get_profile_image_path, verbose_name='Изображение профиля'),
        ),
        migrations.AlterField(
            model_name='album',
            name='img_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='img_cover_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='img_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='img_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_profile_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение профиля (устаревшее)'),
        ),
    ]
