# Generated by Django 5.0.6 on 2025-05-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaudio', '0005_statistics_album_cover_image_artist_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='img_cover_url',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='track',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_profile_url',
        ),
    ]
