# Generated by Django 5.0.6 on 2025-06-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaudio', '0009_albumreview_trackreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь'), ('artist', 'Исполнитель'), ('moderator', 'Модератор')], default='user', max_length=10, verbose_name='Роль'),
        ),
    ]
