# Generated by Django 5.0.6 on 2025-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaudio', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('play', 'Воспроизведение'), ('like', 'Лайк'), ('like_album', 'Лайк альбома'), ('add_to_playlist', 'Добавление в плейлист'), ('remove_from_playlist', 'Удаление из плейлиста'), ('follow_artist', 'Подписка на исполнителя')], max_length=20, verbose_name='Тип активности'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type'], name='kaudio_user_user_id_beacb0_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['timestamp'], name='kaudio_user_timesta_706976_idx'),
        ),
    ]
