# Generated by Django 5.0.6 on 2025-06-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaudio', '0011_alter_useractivity_activity_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(condition=models.Q(('album__isnull', False)), fields=('title', 'album'), name='unique_track_title_in_album'),
        ),
    ]
