# Generated by Django 5.0.6 on 2025-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaudio', '0012_track_unique_track_title_in_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='avg_rating',
            field=models.FloatField(default=0, verbose_name='Средний рейтинг'),
        ),
    ]
