# Generated by Django 5.0.6 on 2025-06-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaudio', '0013_track_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность (сек)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='track',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='Количество воспроизведений'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер трека'),
        ),
    ]
