# Generated by Django 5.0.6 on 2025-06-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaudio', '0014_alter_track_avg_rating_alter_track_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='play_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний'),
        ),
    ]
