# Generated by Django 5.0.6 on 2025-06-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaudio', '0015_album_play_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='track',
            name='unique_track_title_in_album',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='usersubscribe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='permissions',
            field=models.TextField(blank=True, verbose_name='Права и ограничения'),
        ),
        migrations.AlterField(
            model_name='useralbum',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='usertrack',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['track'], name='kaudio_user_track_i_9d3e47_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['album'], name='kaudio_user_album_i_c4a0ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('album', 'track_number'), name='unique_track_number_in_album'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('album', 'title'), name='unique_track_title_in_album'),
        ),
    ]
